function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 19-Apr-2019 11:28:10

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1);
set(plot1(1),'DisplayName','Legacy and Athlete','LineStyle','--','Color',[0 0 0]);
set(plot1(2),'DisplayName','NLNA','Color',[0 0 0]);
text(2008,0.73,'NLNA');
text(2007,0.895,'Legacy and Athlete');

% Create ylabel
ylabel({'Matriculation Rate'});

% Create xlabel
xlabel({'Harvard Class'});

% Uncomment the following line to preserve the X-limits of the axes
 xlim(axes1,[2000 2017]);
% Uncomment the following line to preserve the Y-limits of the axes
 ylim(axes1,[0.65 0.95]);
box(axes1,'on');
% Create legend
%legend(axes1,'show');

% Save as pdf fit to image size
set(gcf,'Units','inches');
screenposition = get(gcf,'Position');
set(gcf,...
    'PaperPosition',[0 0 screenposition(3:4)],...
    'PaperSize',[screenposition(3:4)]);
print -dpdf -painters FiguresAndTables/matric


